server:
  port: 8082
spring:
  application:
    name: mentorapp-expertise
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
  elasticsearch:
    rest:
      uris: localhost:9200
eureka:
  client:
      serviceUrl:
         defaultZone: https://mentorapp-serviceregistry.herokuapp.com/eureka/
admin:
  authtoken: dHJhaW5pbmc6cGFzc3dvcmQ=